version: "3.3"

services:

  api:
    build:
      context: .
    image: fintech_api
    env_file: docker-compose.env
    environment:
      PORT: 443
    depends_on:
      - nats
      - redis
    labels:
      - "traefik.enable=true"
      # - "traefik.http.middlewares.justredirect.redirectscheme.scheme=https"
      # - "traefik.http.middlewares.justredirect.redirectscheme.permanent=true"
      # - "traefik.http.routers.api-gw.middlewares=justredirect"
      - "traefik.http.routers.api-gw.rule=Host(`localhost`)"
      - "traefik.http.routers.api-gw.entrypoints=web"
      - "traefik.http.routers.api-gws.rule=Host(`localhost`)"
      - "traefik.http.routers.api-gws.entrypoints=websecure"
      - "traefik.http.routers.api-gws.tls.certresolver=mylogi"
      - "traefik.http.services.api-gws.loadbalancer.server.port=443"
    networks:
      - internal

  mysql:
    image: mysql
    restart: on-failure
    environment:
      POSTGRES_USER: ulimo_us
      POSTGRES_PASSWORD: fgdsrkdhhjwghbj
      POSTGRES_DB: users
    ports:
      - 3306:3306
    volumes:
      - ulimodata:/var/lib/postgresql/data
      - ./dbscripts/postgres:/docker-entrypoint-initdb.d
    networks:
      - internal

  traefik:
    image: traefik:v2.1
    command:
      - "--api.insecure=false" # Don't do that in production!
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mylogi.acme.httpchallenge=true"
      - "--certificatesresolvers.mylogi.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.mylogi.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.mylogi.acme.email=hello@echwood.com"
      - "--certificatesresolvers.mylogi.acme.storage=/letsencrypt/acme.json"
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./letsencrypt:/letsencrypt"
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal
      - default

networks:
  internal:

volumes:
  ulimodata:
